Add story tags attribute
iftechfoundation/twine-specs pull request #15
Opened 2021-05-12 02:48 UTC by klembot

This is a forthcoming change in Twine 2.4. An early form of this functionality has landed on [the develop branch](https://github.com/klembot/twinejs/tree/develop) if you'd like to take a look, but keep in mind that the code is in pre-alpha state and could easily trash any existing stories/cause weird issues if you downgrade to 2.3.

2021-08-28 14:29 UTC, tmedwards requested changes
See comment.

2021-08-28 14:29 UTC, tmedwards commented on twine-2-htmloutput-spec.md
> +* tags (string) Optional. A list of tags assigned to the story by its author, with spaces separating them.
You're missing a colon after the initial `tags`.  E.g.,

```
* tags: (string) …
```

2021-08-28 22:08 UTC, greyelf commented
I'm curious about the initial purposed of this new story level tag.

2021-08-29 01:55 UTC, tmedwards commented
For author tags—as discussed in today's committee meeting.

Presumably for things like genre and content tags, as one example.

2022-08-27 14:30 UTC, mcdemarco commented
Sounds good.

2022-09-25 14:08 UTC, merged