Historical Twine 1 HTML Documentation
iftechfoundation/twine-specs pull request #20
Opened 2023-07-05 01:42 UTC by videlais

This commit adds documentation on Twine 1 HTML as best as I could reverse-engineer it from the Twine 1 Python code and many examples from the IFDB. This probably won't be used by many people, but as someone who has been trying to analyze older Twine 1 works this week, a document like this would have been really useful to consult.

If there is anything wrong, please let me know or edit before committing. I'd like it to be as accurate as possible for future historical work.

2023-07-25 14:22 UTC, tmedwards commented
Any updates on this?

2023-07-25 17:19 UTC, videlais commented
@tmedwards If you are asking me, the only thing remaining, I think, is how best to handle the cases I've seen where some stories made with Twine 1.4.2 have ROT13 encoding of their passage names. I have not checked, but does Tweego support parsing those? Is there something you might recommend for other parsing HTML elements with ROT-encoding of passage names where the "Start" passage might not be obvious?

2023-07-25 20:11 UTC, tmedwards commented
@videlais I was referring to the issues (in comments) I raised the day after you made the PR.

----

> If you are asking me, the only thing remaining, I think, is how best to handle the cases I've seen where some stories made with Twine 1.4.2 have ROT13 encoding of their passage names.

You may already know this, but I'll cover it anyway to make sure.

Obfuscation had two distinct flavors in Twine ≥`v1.4.0`:

* **`v1.4.0`–`v1.4.1`:** Used a custom obfuscation key, which was stored in `StorySettings`.
* **≥`v1.4.2`:** Replaced custom obfuscation with ROT13, status stored in `StorySettings`.

IIRC, when enabled, both flavors affected most passages.  Both excluded the `StorySettings` special passage, since it contains the obfuscation settings.  The ≥`v1.4.2` flavor additionally excluded image passages, presumably since Base64 was considered obfuscated enough.


> I have not checked, but does Tweego support parsing those?

No.  I decided early on that I was not supporting either flavor of obfuscation at all.

I could have supported deobfuscation, but IIRC I decided that if I wasn't going to offer full bidirectional support, then it would be better to not have it at all.


> Is there something you might recommend for other parsing HTML elements with ROT-encoding of passage names where the "Start" passage might not be obvious?

My apologies, but I couldn't parse that very well. 😵‍💫

If you ***are not*** asking how I'd suggest decoding obfuscated passages, then please rephrase?

If you *are* asking how I'd suggest decoding obfuscated passages, then the easiest thing would probably be to check the unobfuscated `StorySettings` special passage for the obfuscation settings.  IIRC:

* If `obfuscate` does not exist or does but has the value `off`, then everything should be in cleartext and there's nothing to be done.
* If `obfuscate` exists with the value `swap` and `obfuscatekey` exists, then you should be dealing with `v1.4.0`–`v1.4.1`.  You'll need to use the custom obfuscation method along with the value of `obfuscatekey`.
* If `obfuscate` exists with a value of `rot13` and `obfuscatekey` does not exist, then you should be dealing with ≥`v1.4.2`.  You'll need to use ROT13.

Both flavors encoded the tiddler's title, tags, and content.

For the exact code details, you'll need to check the `tweecode/twine` repository.  You'll find the custom obfuscation method there and, in both cases, the precise steps the original code used.

2023-07-25 21:02 UTC, videlais commented on twine-1-htmloutput-doc.md
> +# Twine 1 HTML Output Documentation (v1.0)
Test comment.

2023-07-25 21:12 UTC, videlais commented
@tmedwards I'm confused. I did not and still do not see any comments. 

![screenshot](https://github.com/iftechfoundation/twine-specs/assets/1614382/77ac7c3d-ba9e-430a-a39f-2510e9abc8dd)

They would appear under the Conversation tab and trigger a notification. I would be happy to address them, but I don't see them.

![conversations](https://github.com/iftechfoundation/twine-specs/assets/1614382/b2e86345-0829-4516-941f-63f38e0e7f12)


From my perspective, the question "Any updates on this?" was the first response I had seen in three weeks.

---

Yes, thank you. I was asking about if Tweego did (it does not, for a good reason) and how you might recommend others do it. I do not know if your comments addressed it, probably they did, but that was my last item to include in the documentation. Like you mentioned, different versions of Twine obfuscated things in different ways, and I wanted to make sure that was recorded.

2023-07-25 21:29 UTC, tmedwards commented
> I'm confused. I did not and still do not see any comments. 

Strange.  I can, obviously, see them in the GitHub mobile client and on the website.

![image](https://github.com/iftechfoundation/twine-specs/assets/101626/9c5a02e9-5389-4fa5-a205-7ead46d75ef5)

![image](https://github.com/iftechfoundation/twine-specs/assets/101626/53b894e0-81d1-48ad-b487-bf89f995198c)


Apologizes for the poke, but is anyone else having issues seeing the comments?

**Cc:** @klembot @greyelf @mcdemarco

2023-07-25 21:39 UTC, tmedwards commented
Maybe this will work? 
https://github.com/iftechfoundation/twine-specs/pull/20#pullrequestreview-1514712102

2023-07-26 00:35 UTC, mcdemarco commented
> @tmedwards (and @videlais )
> I **don't** see your "tmedwards has pending changes" entry, or the related 6 comments, in the flow of this pull request, except in the screen capture you supplied. Nor did I find anything similar in the committed file itself.

I think the six comments are in this thread (before greyelf's, in the conversation on the pull request).  I assume there's some review of tme's that I also cannot see despite clicking around the github website a bit, that he quotes later on in this thread.

2023-07-28 18:02 UTC, tmedwards requested changes
Fnord?

2023-07-28 18:08 UTC, tmedwards commented
That *seems* to have worked. 🤞 

You used to be able to simply comment on commits and PRs.  I wonder if you cannot anymore or if I accidentally started a review.

2023-07-28 19:23 UTC, videlais commented
Thanks, @tmedwards! I can now see the comments and I will start to make corrections and clarifications within the next few days.

2023-08-06 19:56 UTC, videlais commented on twine-1-htmloutput-doc.md
> +The root of a Twine 1 story is an element with the `id` of `storeArea`. Inside of this are passages encoded as children with each containing the `tiddler` attribute along with a value for the name of
Noted.

2023-08-07 00:50 UTC, videlais commented on twine-1-htmloutput-doc.md
> +* twine-position: (string) Required. The X and Y coordinates of the passage within Twine 1 separated by a comma.
Updated.

2023-08-07 01:04 UTC, videlais commented on twine-1-htmloutput-doc.md
> +Passage content is stored within the element itself as a single text node and must contain no other child nodes; all `&`, `<`, `>`, `"`, and `'` characters should be escaped into their corresponding
Added.

2023-08-07 01:04 UTC, videlais commented on twine-1-htmloutput-doc.md
> +
Updated.

2023-08-07 01:20 UTC, videlais commented on twine-1-htmloutput-doc.md
> +Beginning with Twine 1.4, the story stylesheet is included as a child `<style>` element of the `<head>` element using the `id` attribute value of `"storyCSS"`.
Updated.

2023-08-07 01:23 UTC, videlais reviewed
Updated based on comments.

2023-08-15 14:57 UTC, tmedwards approved these changes

2023-08-15 14:58 UTC, tmedwards commented
LGTM. 👍🏻

2023-08-15 14:59 UTC, merged